# Generated by Django 4.2.11 on 2024-05-02 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_book_image_book_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
